### ISSUE TITLE
can you build a bin for "mvebu"

### ISSUE THREAD

**Issue by ohyeah521** [hw-cookbooks/dnsmasq#20]
i had a router "linksys wrt1900ac" , so i need this bin. thank you.

**Comment by chrisroberts** [comment]
Hello. This is the incorrect code repository. We cannot build this for you. There are packages built for mvebu. The bin can probably be extracted from the package. Package list:

https://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/base/

Link to the full dnsmasq package:

https://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/base/dnsmasq-full_2.75-2_mvebu.ipk

If you need more help, the openwrt documentation will be able to provide more help than us: http://wiki.openwrt.org/doc/start

Cheers!

**Comment by ohyeah521** [comment]
@chrisroberts    thank you for your help.
